import json
from pathlib import Path

import chromadb

from embedding_client import embed_texts


PROJECT_ROOT = Path(__file__).resolve().parents[1]

CHUNKS_FILE = PROJECT_ROOT / "outputs" / "document_chunks.json"
VECTOR_STORE_DIR = PROJECT_ROOT / "vector_store" / "chroma_db"

COLLECTION_NAME = "presales_knowledge_base"


def load_chunks() -> list[dict]:
    """
    Load document chunks generated by chunk_documents.py.
    """

    if not CHUNKS_FILE.exists():
        raise FileNotFoundError(
            f"Chunks file not found: {CHUNKS_FILE}\n"
            "Please run: python rag_app\\chunk_documents.py"
        )

    return json.loads(CHUNKS_FILE.read_text(encoding="utf-8"))


def reset_collection(client: chromadb.PersistentClient):
    """
    Delete the existing Chroma collection if it exists,
    then create a fresh collection.

    This keeps the vector store clean and avoids duplicate chunks.
    """

    try:
        client.delete_collection(COLLECTION_NAME)
        print(f"Deleted existing collection: {COLLECTION_NAME}")
    except Exception:
        print(f"No existing collection found: {COLLECTION_NAME}")

    collection = client.create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"},
    )

    return collection


def build_vector_store() -> None:
    """
    Build a local Chroma vector store from document chunks.

    Workflow:
    1. Load chunks from outputs/document_chunks.json
    2. Generate embeddings for chunk texts
    3. Store chunk text, metadata, and embeddings in Chroma
    """

    chunks = load_chunks()

    if not chunks:
        raise ValueError("No chunks found. Please check document_chunks.json.")

    print(f"Loaded {len(chunks)} chunks.")

    texts = [chunk["text"] for chunk in chunks]
    ids = [chunk["chunk_id"] for chunk in chunks]

    metadatas = [
        {
            "source_file": chunk["source_file"],
            "chunk_index": chunk["chunk_index"],
        }
        for chunk in chunks
    ]

    print("Generating embeddings for chunks...")
    embeddings = embed_texts(texts)

    print(f"Generated {len(embeddings)} embeddings.")

    VECTOR_STORE_DIR.mkdir(parents=True, exist_ok=True)

    client = chromadb.PersistentClient(path=str(VECTOR_STORE_DIR))
    collection = reset_collection(client)

    print("Writing chunks into Chroma vector store...")

    collection.add(
        ids=ids,
        documents=texts,
        metadatas=metadatas,
        embeddings=embeddings,
    )

    print("\nVector store built successfully.")
    print(f"Chroma path: {VECTOR_STORE_DIR}")
    print(f"Collection name: {COLLECTION_NAME}")
    print(f"Total chunks stored: {collection.count()}")


if __name__ == "__main__":
    build_vector_store()