import json
from pathlib import Path

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CHUNKS_FILE = PROJECT_ROOT / "outputs" / "document_chunks.json"


def load_chunks() -> list[dict]:
    """
    Load document chunks generated by chunk_documents.py.
    """

    if not CHUNKS_FILE.exists():
        raise FileNotFoundError(
            f"Chunks file not found: {CHUNKS_FILE}\n"
            "Please run: python rag_app\\chunk_documents.py"
        )

    return json.loads(CHUNKS_FILE.read_text(encoding="utf-8"))


def retrieve_relevant_chunks(
    question: str,
    top_k: int = 5,
) -> list[dict]:
    """
    Retrieve the most relevant chunks for a user question using TF-IDF.

    TF-IDF is a simple local retrieval method.
    It does not require API keys, embeddings, or vector databases.
    """

    chunks = load_chunks()
    chunk_texts = [chunk["text"] for chunk in chunks]

    vectorizer = TfidfVectorizer(
        stop_words="english",
        lowercase=True,
        max_features=5000,
    )

    # Convert all chunks into TF-IDF vectors
    chunk_vectors = vectorizer.fit_transform(chunk_texts)

    # Convert user question into the same vector space
    question_vector = vectorizer.transform([question])

    # Calculate similarity between question and every chunk
    similarities = cosine_similarity(question_vector, chunk_vectors).flatten()

    # Get top-k most relevant chunk indexes
    top_indexes = similarities.argsort()[::-1][:top_k]

    results = []

    for rank, index in enumerate(top_indexes, start=1):
        chunk = chunks[index].copy()
        chunk["rank"] = rank
        chunk["similarity_score"] = round(float(similarities[index]), 4)
        results.append(chunk)

    return results


def print_retrieval_results(question: str, results: list[dict]) -> None:
    """
    Print retrieval results in a readable format.
    """

    print("\nQuestion:")
    print(question)

    print("\nTop retrieved chunks:")
    print("=" * 80)

    for item in results:
        print(f"\nRank: {item['rank']}")
        print(f"Similarity Score: {item['similarity_score']}")
        print(f"Source File: {item['source_file']}")
        print(f"Chunk ID: {item['chunk_id']}")
        print("-" * 80)
        print(item["text"][:700])
        print("=" * 80)


if __name__ == "__main__":
    sample_question = "Can InsightFlow AI connect to MySQL and Power BI?"

    retrieved_chunks = retrieve_relevant_chunks(
        question=sample_question,
        top_k=5,
    )

    print_retrieval_results(sample_question, retrieved_chunks)